spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle9iDialect

  datasource:
    password: ${DATABASE_USER:DOM_B2B_4}
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    username: ${DATABASE_PASSWD:DOM_B2B_4}
    url: jdbc:tibero:thin:@${DATABASE_IP:220.90.208.123}:${DATABASE_PORT:8629}:tibero
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  aop:
    proxy-target-class: 'true'